
await page.getByRole('textbox', { name: 'First Name' }).click();
await page.goto('https://www.hyrtutorials.com/p/css-selectors-practice.html?utm_source=chatgpt.com#google_vignette');
await page.getByRole('textbox', { name: 'First Name' }).fill('');
await page.getByRole('textbox', { name: 'Last Name' }).click();
await page.getByRole('textbox', { name: 'Last Name' }).fill('');
await page.getByRole('textbox', { name: 'Gender' }).click();
await page.getByRole('textbox', { name: 'Gender' }).fill('');
await page.getByRole('textbox', { name: 'City' }).click();
await page.getByRole('textbox', { name: 'City' }).fill('');
await page.getByRole('textbox', { name: 'Country' }).click();
await page.getByRole('textbox', { name: 'Country' }).fill('');
await page.getByRole('textbox', { name: 'Enter your security question' }).click();
await page.getByRole('textbox', { name: 'Enter your security question' }).fill('');
await page.getByRole('textbox', { name: 'Enter your security answer' }).click();
await page.getByRole('textbox', { name: 'Enter your security answer' }).fill('');
await page.getByRole('textbox', { name: 'Verify your personal details' }).click();
await page.getByRole('textbox', { name: 'Verify your personal details' }).fill('');
await page.getByRole('combobox').first().selectOption('select');
await page.getByRole('checkbox').uncheck();
await page.getByRole('button', { name: 'Buttton1' }).click();
await page.getByRole('combobox').nth(1).selectOption('select');
await page.getByRole('textbox', { name: 'First Name' }).click();
await page.getByRole('textbox', { name: 'First Name' }).fill('maaenna');
await page.getByRole('textbox', { name: 'Last Name' }).click();
await page.getByRole('textbox', { name: 'Last Name' }).fill('A');
await page.getByRole('textbox', { name: 'Gender' }).click();
await page.getByRole('textbox', { name: 'Gender' }).fill('Female');
await page.getByRole('textbox', { name: 'City' }).click();
await page.getByRole('textbox', { name: 'City' }).fill('tamil');
await page.getByRole('textbox', { name: 'Country' }).click();
await page.getByRole('textbox', { name: 'Country' }).fill('india');
await page.getByRole('textbox', { name: 'Enter your security question' }).click();
await page.getByRole('textbox', { name: 'Enter your security question' }).fill('pet name');
await page.getByRole('textbox', { name: 'Enter your security answer' }).click();
await page.getByRole('textbox', { name: 'Enter your security answer' }).fill('tene');
await page.getByRole('textbox', { name: 'Verify your personal details' }).click();
await page.getByRole('textbox', { name: 'Verify your personal details' }).fill('yes');
await page.getByRole('combobox').first().selectOption('apple');
await page.getByRole('checkbox').check();
await page.getByRole('button', { name: 'Buttton1' }).click();
await page.getByRole('combobox').nth(1).selectOption('js');
await page.getByRole('link', { name: 'Click Here', exact: true }).click();